---
title: "Acosta-Worksheet7"
author: "ACOSTA, MELBOURNE  BSIT2A"
date: "2022-12-22"
output: pdf_document
---

```{r , include=TRUE}

```

```{r , include=TRUE}
#1. Create a data frame for the table below 

Student <- seq(1:10)
PreTest <- c(55,54,47,57,51,61,57,54,63,58)
PostTest <- c(61,60,56,63,56,63,59,56,62,61)

DF <- data.frame(Student,PreTest,PostTest)
DF
```

```{r , include=TRUE}
#a. Compute the descriptive statistics using different packages (Hmisc and pastecs).

#Write the codes and its result.

library(Hmisc)
library(pastecs)

describe(DF)

stat.desc(DF)
```

```{r , include=TRUE}
#2. The Department of Agriculture was studying the effects of several levels of a
#fertilizer on the growth of a plant. For some analyses, it might be useful to convert
#the fertilizer levels to an ordered factor.

DepartmentofAgriculture <- c(10,10,10,20,20,50,10,
                             20,10,50,20,50,20,10)

```

```{r , include=TRUE}
#a. Write the codes and describe the result.
In_Ord <- sort(DepartmentofAgriculture, decreasing = FALSE)
In_Ord
```

```{r , include=TRUE}
#3. Abdul Hassan, president of Floor Coverings Unlimited, has asked you to study
#the exercise levels undertaken by 10 subjects were “l”, “n”, “n”, “i”, “l” ,
#“l”, “n”, “n”, “i”, “l” ; n=none, l=light, i=intense
Subjects <- c("l","n","n","i","l","l","n","n","i","l")
```

```{r , include=TRUE}
#a. What is the best way to represent this in R?

#DATAFRAME
out <- data.frame(Subjects)
out

```

```{r , include=TRUE}
#4.Sample of 30 tax accountants from all the states and territories of Australia and
#their individual state of origin is specified by a character vector of state mnemonics
#as:
state <- c("tas", "sa", "qld", "nsw", "nsw", "nt", "wa", "wa", "qld",
           "vic", "nsw", "vic", "qld", "qld", "sa", "tas", "sa", "nt",
           "wa", "vic", "qld", "nsw", "nsw", "wa", "sa", "act", "nsw",
           "vic", "vic", "act")
state  
```

```{r , include=TRUE}
#a. Apply the factor function and factor level. Describe the results.
hello <- function(state)
  hello 
```

```{r , include=TRUE}
#5. From #4 - continuation:

#• Suppose we have the incomes of the same tax accountants in another vector (in
incomes <- c(60, 49, 40, 61, 64, 60, 59, 54,
             62, 69, 70, 42, 56, 61, 61, 61, 58, 51, 48,
             65, 49, 49, 41, 48, 52, 46, 59, 46, 58, 43)
```

```{r , include=TRUE}
#a. Calculate the sample mean income for each state we can now use the special
#function tapply():
Calc <- tapply(state, incomes, mean)
Calc
```

```{r , include=TRUE}
#b. Copy the results and interpret.
# 40 41 42 43 46 48 49 51 52 54 56 58 59 60 61 62 64 65 69 70 
#NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
```

```{r , include=TRUE}
#6.Calculate the standard errors of the state income means (refer again to number 3)

Calc_ST.n <- length(Calc)
Calc_1.sd <- sd(Calc)
Calc_Final.se <- Calc_1.sd/sqrt(Calc_ST.n)
Calc_Final.se

```

```{r , include=TRUE}
#a. What is the standard error? Write the codes.
#NA
```

```{r , include=TRUE}
#b. Interpret the result.
#the result is not available because some variables are character type so it won't able to get the standard error.
```

```{r , include=TRUE}
#7. Use the titanic dataset.
data("Titanic")

head<- data.frame(Titanic)
```

```{r , include=TRUE}
#a. subset the titatic dataset of those who survived and not survived. Show the
#codes and its result.
head_subset <- subset(head, select = "Survived")
head_subset
```

```{r , include=TRUE}
#8. The data sets are about the breast cancer Wisconsin. The samples arrive periodically as Dr. Wolberg reports his clinical cases. The database therefore reflects this
#chronological grouping of the data. You can create this dataset in Microsoft Excel.

```

```{r , include=TRUE}
#a. describe what is the dataset all about.
#The dataset is all about Breast Cancer.

```

```{r , include=TRUE}
#b. Import the data from MS Excel. Copy the codes.

library("readxl")
DATA <- read_excel("B:\\Git\\Worksheets\\Acsota_Workesheet7\\Breast_Cancer.xlsx")
DATA
```

```{r , include=TRUE}
#c. Compute the descriptive statistics using different packages. Find the values of:

#c.1 Standard error of the mean for clump thickness.
Clump <- length(DATA$`CL. thickness`)
Clump_A <- sd(DATA$`CL. thickness`)
Clump_B <- Clump_A/sqrt(DATA$`CL. thickness`)
Clump_B
```

```{r , include=TRUE}
#c.2 Coefficient of variability for Marginal Adhesion.
COV <- sd(DATA$`Marg. Adhesion`) / mean(DATA$`Marg. Adhesion`)* 100
COV
```

```{r , include=TRUE}
#c.3 Number of null values of Bare Nuclei.
Null_Values <- subset(DATA,`Bare. Nuclei` == "NA")
```

```{r , include=TRUE}
#c.4 Mean and standard deviation for Bland Chromatin
mean(DATA$`Bl. Cromatin`)
sd(DATA$`Bl. Cromatin`)
```

```{r , include=TRUE}
#c.5 Confidence interval of the mean for Uniformity of Cell Shape

#Calculate the mean
Calc_Mean <- mean(DATA$`Cell Shape`)
Calc_Mean

```

```{r , include=TRUE}
#Calculate the standard error of the mean
SE_M <- length(DATA$`Cell Shape`)
SD_B <- sd(DATA$`Cell Shape`)
Ans_1 <- SD_B/sqrt(SE_M)
Ans_1
```

```{r , include=TRUE}
#Find the t-score that corresponds to the confidence level
D = 0.05
numE = SE_M - 1
numF = qt(p = D/ 2, df = numE,lower.tail = F)
numF
```

```{r , include=TRUE}
#Constructing the confidence interval
numG <- numF * numE
```

```{r , include=TRUE}
#Lower
numH <- Calc_Mean - numG
```

```{r , include=TRUE}

#Upper
numI <- Calc_Mean + numG

c(numH,numI)

```

```{r , include=TRUE}
#d. How many attributes?
attributes(DATA)
```

```{r , include=TRUE}
#e. Find the percentage of respondents who are malignant. Interpret the results.
P_R <- subset(DATA, Class == "maligant")
P_R
```

```{r , include=TRUE}
#There 17 respondents who are malignant.
#And there are total of 49 respondent.
```

```{r , include=TRUE}
#Getting the percentage
17  / 49 * 100
```

```{r , include=TRUE}
#9. Export the data abalone to the Microsoft excel file. Copy the codes.

library("AppliedPredictiveModeling")
data("abalone")
View(abalone)
head(abalone)
summary(abalone)
```

```{r , include=TRUE}
#Exporting the data abalone to the Microsoft excel file

library(xlsx)
write.xlsx("abalone","B:\\Git\\Worksheets\\Acsota_Workesheet7\\abalone.xlsx")
```

