---
title: "Acosta-Worksheet4"
author: "ACOSTA, MELBOURNE  BSIT2A"
date: "2022-12-11"
output: pdf_document
---

```{r , include=TRUE}
#1a
Shoesize <- c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,
              7.5,10.5,8.5,12.0,10.5,
              13.0,11.5,8.5,5.0,10.0,
              6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0)

Height <- c(66.0,68.0,64.5,65.0,70.0,
            64.0,70.0,71.0,72.0,64.0,
            74.5,67.0,71.0,71.0,77.0,72.0,
            59.0,62.0,72.0,66.0,64.0,67.0,73.0,
            69.0,72.0,70.0,69.0,70)

Gender <- c("F","F","F","F","M","F","M","F","M",
            "M","M","F","M","M","M","M","F","F",
            "M","F","M","M","M","F","M","M","M","M")

df <- data.frame(Shoesize,Height,Gender)
df

```

```{r , include=TRUE}
#b
summary(df)
# SHOESIZE: Mean   : 9.411
# HEIGHT:   Mean   :68.57
```
```{r , include=TRUE}
#c
#Yes, The Higher the height, the greater the shoesize.

#the factor levels below the actual values.

Months <- c("March","April","January","November","January",
            "September","October","September","November","August",
            "January","November","November","February","May","August",
            "July","December","August","August","September","November","February","April")

factor_Months <- factor(Months)
factor_Months
```
```{r , include=TRUE}
#3. Then check the summary() of the months_vector and factor_months_vector. |
#Interpret the results of both vectors. Are they both equally useful in this case?
summary(Months)

summary(factor_Months)

```
```{r , include=TRUE}
#4.
factor_data <- c(1,4,3)


new_order_data <- factor(factor_data,levels = c("East","West","North"))

print(new_order_data)

```

