---
title: "Individual-Project1"
author: "ACOSTA, MELBOURNE  BSIT2A"
date: "2022-12-21"
output: html_document
---

```{r , include=TRUE}
library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)
library(rtweet)
```

```{r , include=TRUE}
# SETUP CREDENTIALS.
CONSUMER_KEY <- "CrXArDLAgmPuQOxVurcBrk3Ez"
CONSUMER_SECRET <- "EQoqQclSB6qwJMcqYrYC80yWBFrT85t1UBEcgP3L4Gge4xeOOP"
ACCESS_TOKEN <-  "1597217544519045120-oZ7NYrQDw5QW4CjCHiO4v9qx9Td2QD"
ACCESS_SECRET <-  "kNlFVVkanyJWXzZfNQmohCZSWlnfGAfVLhzySNEZur2cR"

setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)
```

```{r , include=TRUE}
# EXTRACTING TWEETS.
data_tweets <- searchTwitter("#Japan -filter:retweets", n=10000, lang="en", 
                             since="2022-12-14", until="2022-12-21", 
                             retryOnRateLimit = 120)
data_tweets
```

```{r , include=TRUE}
# CONVERTING LIST DATA TO DATA FRAME.
tweetsDF <- twListToDF(data_tweets)
class(tweetsDF)
names(tweetsDF)
View(tweetsDF)
head(tweetsDF)[1:5]
head(tweetsDF$text)[1:5]
```

```{r , include=TRUE}
# SAVE DATA FRAME FILE.
save(tweetsDF,file = "trendingTweetsDF.Rdata")
```

```{r , include=TRUE}
# LOAD DATA FRAME FILE.
load(file = "trendingTweetsDF.Rdata")
```

```{r , include=TRUE}
# CHECKING FOR MISSING VALUES IN A DATA FRAME.
data_chk <- sapply(tweetsDF, function(x) sum(is.na(x)))
data_chk
```

```{r , include=TRUE}
# SUBSETTING USING THE dplyr() PACKAGE.
tweetsDF2 <- tweetsDF %>%
  select(screenName,text,created,statusSource)
tweetsDF2
```

```{r , include=TRUE}
# GROUPING THE DATA CREATED. 
tweetsDF2 %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))
```

```{r , include=TRUE}
#Adding column for Created at Round data
data_create <- tweetsDF %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
data_create

tweetsDF2 %>% pull(created) %>% min() 
tweetsDF2 %>% pull(created) %>% max()
```

```{r , include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plt_data <- data_create %>% 
  dplyr::count(Created_At_Round) %>% 
  ggplot(mapping = aes(x = Created_At_Round, y = n)) +
  theme_light() +
  geom_line() +
  xlab(label = 'Date') +
  ylab(label = NULL) +
  ggtitle(label = 'Number of Tweets per Hour')

plt_data %>% ggplotly()
```

```{r , include=TRUE}
#pseodu plotting that has a legend
ggplot(data = tweetsDF, aes(x = created)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")

```

```{r , include=TRUE}
# PLOTTING STATUS SOURCE.
encodeSource <- function(x) {
  if(grepl(">Twitter for iPhone</a>", x)){
    "iphone"
  }else if(grepl(">Twitter for iPad</a>", x)){
    "ipad"
  }else if(grepl(">Twitter for Android</a>", x)){
    "android"
  } else if(grepl(">Twitter Web Client</a>", x)){
    "Web"
  } else if(grepl(">Twitter for Windows Phone</a>", x)){
    "windows phone"
  }else if(grepl(">dlvr.it</a>", x)){
    "dlvr.it"
  }else if(grepl(">IFTTT</a>", x)){
    "ifttt"
  }else if(grepl(">Facebook</a>", x)){  #This looks unreliable...
    "facebook"
  }else {
    "others"
  }
}

```

```{r , include=TRUE}
#applying encodeSource funtion in the tweetsDF data
tweetsDF2$tweetSource = sapply(tweetsDF$statusSource, 
                               encodeSource)
```

```{r , include=TRUE}
#Converting to dataframe
data_appSource <- tweetsDF2 %>% 
  select(tweetSource) %>%
  group_by(tweetSource) %>%
  summarize(count=n()) %>%
  arrange(desc(count))
```

```{r , include=TRUE}
#plotting for tweetSource 
ggplot(tweetsDF2[tweetsDF2$tweetSource != 'others',], aes(tweetSource, fill = tweetSource)) +
  geom_bar() +
  theme(legend.position="none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of tweets") +
  ggtitle("Tweets by Source")
```

```{r , include=TRUE}
# Accounts that tweeted from the trentopic Japan.
data_appScreen <- tweetsDF2 %>%
  select(screenName) %>%
  group_by(screenName) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 
```

```{r , include=TRUE}
#convert to Corpus
namesCorpus_data <- Corpus(VectorSource(data_appScreen$screenName))  #using ScreenName
class(data_appScreen$screenName)

cls <- class(VectorSource(data_appScreen$screenName))
cls

str(namesCorpus_data)

class(namesCorpus_data)

nms <- namesCorpus_data
nms
```

```{r , include=TRUE}
# Wordcloud for the screenNames.
word_pal <- brewer.pal(8, "Dark2")
pal_word <- word_pal[-(1:4)]
set.seed(123)

par(mar = c(0,0,0,0), mfrow = c(1,1))

wordcloud(words = namesCorpus_data, scale=c(3,0.5),
          max.words=10000,
          random.order=FALSE,
          rot.per=0.5,
          use.r.layout=TRUE,
          colors=pal_word)
```

